### ISSUE TITLE
Is okta-oidc-tck good for stubbing Okta in integration tests?

### ISSUE THREAD

**Issue by msbober** [okta/okta-oidc-tck#51]
So, maybe I got it completely wrong, but, is okta-oidc-tck an Okta stub that can be used by products integrating with Okta in their integration tests? Thanks!

**Comment by bdemers** [comment]
@msbober sorry for the delay (i had my notifications setup incorrectly)
You might have noticed this already, but no. This project is for testing Okta's libraries and Samples against a few specific cases.

If you are still looking what are you trying to mock out? maybe we can point you in the right direction?
